=== konattsu/cliplayer/tools/music.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "VideoData",
  "type": "array",
  "additionalItems": false,
  "items": {
    "type": "object",
    "required": ["videoId", "videoTags", "clips"],
    "additionalProperties": false,
    "properties": {
      "videoId": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_-]{11}$"
      },
      "uploaderName": {
        "type": ["string", "null"],
        "minLength": 1
      },
      "videoTags": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": ".+"
        },
        "minItems": 1
      },
      "clips": {
        "type": "array",
        "additionalProperties": false,
        "minItems": 1,
        "items": {
          "type": "object",
          "required": ["songTitle", "liverIds", "startTime", "endTime"],
          "additionalProperties": false,
          "properties": {
            "songTitle": { "type": ["string"], "minLength": 1 },
            "liverIds": {
              "type": "array",
              "items": { "type": "string", "minLength": 1 },
              "minItems": 1
            },
            "externalArtistsName": {
              "type": ["array", "null"],
              "items": { "type": "string" },
              "minItems": 0
            },
            "clippedVideoId": {
              "type": ["string", "null"],
              "pattern": "^[A-Za-z0-9_-]{11}$"
            },
            "startTime": {
              "type": "string",
              "pattern": "^PT([0-9]+H)?([0-9]+M)?([0-9]+S)?$"
            },
            "endTime": {
              "type": "string",
              "pattern": "^PT([0-9]+H)?([0-9]+M)?([0-9]+S)?$"
            },
            "clipTags": {
              "type": ["array", "null"],
              "items": {
                "type": "string",
                "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
              },
              "minItems": 0
            }
          }
        }
      }
    }
  }
}

=== konattsu/cliplayer/music/data/input/a.json
[
  {
    "videoId": "cFc9Ywpk0QU",
    "uploaderName": null,
    "videoTags": ["2d", "karaoke"],
    "clips": [
      {
        "songTitle": "ふわふわ時間",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT3M2S",
        "endTime": "PT6M56S",
        "clipTags": null
      },
      {
        "songTitle": "妄想感傷代償連盟",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT9M39S",
        "endTime": "PT13M58S",
        "clipTags": null
      },
      {
        "songTitle": "IRIS OUT",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT17M15S",
        "endTime": "PT19M41S",
        "clipTags": null
      },
      {
        "songTitle": "たぶん",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT23M13S",
        "endTime": "PT27M28S",
        "clipTags": null
      },
      {
        "songTitle": "それがあなたの幸せとしても",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT31M23S",
        "endTime": "PT35M7S",
        "clipTags": null
      },
      {
        "songTitle": "神のまにまに",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT36M58S",
        "endTime": "PT41M8S",
        "clipTags": null
      },
      {
        "songTitle": "キミソラキセキ",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT43M36S",
        "endTime": "PT48M36S",
        "clipTags": null
      },
      {
        "songTitle": "恋愛裁判",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT50M15S",
        "endTime": "PT53M54S",
        "clipTags": null
      },
      {
        "songTitle": "ヒッチコック",
        "liverIds": ["sophia-valentine"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT54M58S",
        "endTime": "PT58M40S",
        "clipTags": null
      }
    ]
  }
]

=== konattsu/cliplayer/music/data/input/2026-03-02_08-15-20.json
[
  {
    "videoId": "qfMRqe6hhxs",
    "uploaderName": null,
    "videoTags": [
      "2d",
      "karaoke"
    ],
    "clips": [
      {
        "songTitle": "初恋サイダー",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1M58S",
        "endTime": "PT5M25S",
        "clipTags": null
      },
      {
        "songTitle": "とくベチュ、して",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT8M26S",
        "endTime": "PT12M24S",
        "clipTags": null
      },
      {
        "songTitle": "アララの呪文",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT15M51S",
        "endTime": "PT19M1S",
        "clipTags": null
      },
      {
        "songTitle": "MOON PRIDE",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT21M9S",
        "endTime": "PT24M46S",
        "clipTags": null
      },
      {
        "songTitle": "GO! GO! MANIAC",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT27M27S",
        "endTime": "PT31M31S",
        "clipTags": null
      },
      {
        "songTitle": "MUGO・ん・・・色っぽい",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT34M42S",
        "endTime": "PT38M30S",
        "clipTags": null
      },
      {
        "songTitle": "青空のラプソディ",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT41M8S",
        "endTime": "PT45M42S",
        "clipTags": null
      },
      {
        "songTitle": "I WITH",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT50M8S",
        "endTime": "PT54M52S",
        "clipTags": null
      },
      {
        "songTitle": "おさかな天国",
        "liverIds": [
          "ayane-shirasa"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT57M20S",
        "endTime": "PT1H1M33S",
        "clipTags": null
      }
    ]
  }
]

=== konattsu/cliplayer/music/data/input/2026-03-03_15-25-08.json
[
  {
    "videoId": "5GsswoDivZI",
    "uploaderName": null,
    "videoTags": [
      "2d",
      "karaoke"
    ],
    "clips": [
      {
        "songTitle": "恋の魔法",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT2M",
        "endTime": "PT5M19S",
        "clipTags": null
      },
      {
        "songTitle": "君色に染まる",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT8M59S",
        "endTime": "PT12M10S",
        "clipTags": null
      },
      {
        "songTitle": "風になる",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT15M5S",
        "endTime": "PT19M40S",
        "clipTags": null
      },
      {
        "songTitle": "Campus mode!!",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT25M25S",
        "endTime": "PT29M36S",
        "clipTags": null
      },
      {
        "songTitle": "新宝島",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT31M35S",
        "endTime": "PT36M33S",
        "clipTags": null
      },
      {
        "songTitle": "きらり",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT39M55S",
        "endTime": "PT43M43S",
        "clipTags": null
      },
      {
        "songTitle": "カタオモイ",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT48M30S",
        "endTime": "PT51M58S",
        "clipTags": null
      },
      {
        "songTitle": "火星人",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT53M3S",
        "endTime": "PT56M56S",
        "clipTags": null
      },
      {
        "songTitle": "おねがいダーリン",
        "liverIds": [
          "ruri-shioriha"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT58M40S",
        "endTime": "PT1H1M53S",
        "clipTags": null
      }
    ]
  }
]

=== konattsu/cliplayer/music/data/input/2026-05-06_15-17-07.json
[
  {
    "videoId": "yHCcyyQR_YU",
    "uploaderName": null,
    "videoTags": ["2d", "karaoke"],
    "clips": [
      {
        "songTitle": "あなたといたい",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT2M8S",
        "endTime": "PT5M39S"
      },
      {
        "songTitle": "月に吠える",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT10M30S",
        "endTime": "PT14M54S"
      },
      {
        "songTitle": "melt bitter",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT17M12S",
        "endTime": "PT22M18S"
      },
      {
        "songTitle": "Hello, Again 〜昔からある場所〜",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT24M25S",
        "endTime": "PT29M36S"
      },
      {
        "songTitle": "それがあなたの幸せとしても",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT31M15S",
        "endTime": "PT35M42S"
      },
      {
        "songTitle": "それを愛と呼ぶなら",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT39M52S",
        "endTime": "PT44M42S"
      },
      {
        "songTitle": "DRESSING ROOM",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT46M24S",
        "endTime": "PT49M14S"
      },
      {
        "songTitle": "Same Blue",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT51M28S",
        "endTime": "PT55M21S"
      },
      {
        "songTitle": "片っぽ",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT57M54S",
        "endTime": "PT1H1M34S"
      },
      {
        "songTitle": "泥中に咲く",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H4M41S",
        "endTime": "PT1H9M21S"
      },
      {
        "songTitle": "lulu.",
        "liverIds": ["meruto-kuramochi"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H12M34S",
        "endTime": "PT1H17M5S"
      }
    ]
  }
]

=== konattsu/cliplayer/music/data/input/2026-05-02_16-52-49.json
[
  {
    "videoId": "9DsQFAbuUrs",
    "uploaderName": null,
    "videoTags": ["3d", "karaoke"],
    "clips": [
      {
        "songTitle": "ヘビーローテーション",
        "liverIds": [
          "akari-shishido",
          "roco-kaburaki",
          "ruri-shioriha",
          "salome-hyakumantenbara",
          "yotsuha-umise"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT2M3S",
        "endTime": "PT6M41S",
        "clipTags": null
      },
      {
        "songTitle": "夜もすから君想ふ",
        "liverIds": ["akari-shishido", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT10M40S",
        "endTime": "PT14M33S",
        "clipTags": null
      },
      {
        "songTitle": "恋",
        "liverIds": ["roco-kaburaki", "ruri-shioriha"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT15M44S",
        "endTime": "PT19M53S",
        "clipTags": null
      },
      {
        "songTitle": "君セン！",
        "liverIds": ["akari-shishido", "salome-hyakumantenbara"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT20M53S",
        "endTime": "PT25M",
        "clipTags": null
      },
      {
        "songTitle": "打上花火",
        "liverIds": ["ruri-shioriha", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT25M51S",
        "endTime": "PT30M32S",
        "clipTags": null
      },
      {
        "songTitle": "好きだから。",
        "liverIds": ["akari-shishido", "roco-kaburaki"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT32M7S",
        "endTime": "PT37M",
        "clipTags": null
      },
      {
        "songTitle": "こいのね！",
        "liverIds": [
          "ruri-shioriha",
          "salome-hyakumantenbara",
          "yotsuha-umise"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT38M22S",
        "endTime": "PT41M56S",
        "clipTags": null
      },
      {
        "songTitle": "ジャージ",
        "liverIds": ["roco-kaburaki", "salome-hyakumantenbara"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT43M33S",
        "endTime": "PT46M6S",
        "clipTags": null
      },
      {
        "songTitle": "初恋サイダー",
        "liverIds": ["akari-shishido", "ruri-shioriha", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT47M19S",
        "endTime": "PT50M45S",
        "clipTags": null
      },
      {
        "songTitle": "Pretender",
        "liverIds": ["roco-kaburaki", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT51M45S",
        "endTime": "PT57M4S",
        "clipTags": null
      },
      {
        "songTitle": "輝夜の城で踊りたい",
        "liverIds": [
          "roco-kaburaki",
          "ruri-shioriha",
          "salome-hyakumantenbara"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT58M51S",
        "endTime": "PT1H3M16S",
        "clipTags": null
      },
      {
        "songTitle": "おじゃ虫",
        "liverIds": ["akari-shishido", "ruri-shioriha"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H4M31S",
        "endTime": "PT1H8M6S",
        "clipTags": null
      },
      {
        "songTitle": "UFO",
        "liverIds": ["salome-hyakumantenbara", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H8M45S",
        "endTime": "PT1H12M",
        "clipTags": null
      },
      {
        "songTitle": "君じゃなきゃダメみたい",
        "liverIds": ["akari-shishido", "roco-kaburaki", "yotsuha-umise"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H13M34S",
        "endTime": "PT1H17M25S",
        "clipTags": null
      },
      {
        "songTitle": "恋愛裁判",
        "liverIds": ["ruri-shioriha", "salome-hyakumantenbara"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H18M23S",
        "endTime": "PT1H22M2S",
        "clipTags": null
      },
      {
        "songTitle": "ラブソングに襲われる",
        "liverIds": [
          "akari-shishido",
          "roco-kaburaki",
          "ruri-shioriha",
          "ruri-shioriha",
          "ruri-shioriha",
          "ruri-shioriha",
          "salome-hyakumantenbara",
          "yotsuha-umise"
        ],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H23M49S",
        "endTime": "PT1H27M22S",
        "clipTags": null
      }
    ]
  },
  {
    "videoId": "aJqUz6SccmA",
    "uploaderName": null,
    "videoTags": ["2d", "karaoke"],
    "clips": [
      {
        "songTitle": "倍倍FIGHT!",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT3M51S",
        "endTime": "PT8M3S",
        "clipTags": null
      },
      {
        "songTitle": "タッチ",
        "liverIds": ["ayane-shirasa"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT9M51S",
        "endTime": "PT12M59S",
        "clipTags": null
      },
      {
        "songTitle": "ハイド・アンド・シーク",
        "liverIds": ["madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT14M42S",
        "endTime": "PT17M56S",
        "clipTags": null
      },
      {
        "songTitle": "おこちゃま戦争",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT20M23S",
        "endTime": "PT23M52S",
        "clipTags": null
      },
      {
        "songTitle": "ウミユリ海底譚",
        "liverIds": ["ayane-shirasa"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT25M25S",
        "endTime": "PT29M19S",
        "clipTags": null
      },
      {
        "songTitle": "シカ色デイズ",
        "liverIds": ["madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT30M51S",
        "endTime": "PT34M11S",
        "clipTags": null
      },
      {
        "songTitle": "UNDEAD",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT36M40S",
        "endTime": "PT39M46S",
        "clipTags": null
      },
      {
        "songTitle": "unravel",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT42M4S",
        "endTime": "PT46M",
        "clipTags": null
      },
      {
        "songTitle": "アイワナムチュー",
        "liverIds": ["ayane-shirasa"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT48M37S",
        "endTime": "PT52M",
        "clipTags": null
      },
      {
        "songTitle": "アポリア",
        "liverIds": ["madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT53M21S",
        "endTime": "PT57M5S",
        "clipTags": null
      },
      {
        "songTitle": "ムーンライト伝説",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H",
        "endTime": "PT1H2M51S",
        "clipTags": null
      },
      {
        "songTitle": "恋は渾沌カオスの隷也",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H8M55S",
        "endTime": "PT1H12M52S",
        "clipTags": null
      },
      {
        "songTitle": "ファンサ",
        "liverIds": ["ayane-shirasa"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H19M30S",
        "endTime": "PT1H23M37S",
        "clipTags": null
      },
      {
        "songTitle": "自己肯定感爆上げ↑↑しゅきしゅきソング",
        "liverIds": ["madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H26M32S",
        "endTime": "PT1H30M24S",
        "clipTags": null
      },
      {
        "songTitle": "可不ちゃんのカレーうどん狂騒曲",
        "liverIds": ["ayane-shirasa", "madoka-minamo"],
        "externalArtistsName": null,
        "clippedVideoId": null,
        "startTime": "PT1H30M32S",
        "endTime": "PT1H39M24S",
        "clipTags": null
      }
    ]
  }
]
